language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  # chrome: stable

script:
  - yarn run ng build --base-href "https://khrise.github.io/paperless-frontend/"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist/paperless-frontend
  on:
    branch: master
